01_NumPy_Basics.ipynb

1. Introduction to NumPy
2. What is NumPy?
3. Why NumPy?
4. NumPy Arrays (ndarray)
5. Creating Arrays
6. Dimensions
7. Shape
8. Size
9. Data Types
10. Indexing
11. Slicing
12. Reshaping
13. Flatten
14. Copy vs View
15. Broadcasting
16. Array Operations
17. Universal Functions (ufuncs)

# Introduction to NumPy

NumPy stands for Numerical Python. It is a Python library used for numerical computing.

NumPy provides powerful data structures and functions for working with arrays, mathematical operations, statistics, linear algebra, and scientific computing.

In this notebook, we will learn the basic concepts of NumPy arrays and their operations.

In [2]:
import numpy as np

## 1. What is NumPy?

NumPy is an open-source Python library mainly used for numerical and scientific computing.

It provides a powerful array object called `ndarray`, which allows us to store and process large amounts of numerical data efficiently.

In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


## 2. Why NumPy?

NumPy is useful because:

- It provides fast numerical operations.
- It supports multidimensional arrays.
- It uses less memory than traditional Python lists for numerical data.
- It provides many mathematical functions.
- It is widely used in Data Science, Machine Learning, AI, and scientific computing.

In [4]:
python_list = [1, 2, 3, 4, 5]

numpy_array = np.array([1, 2, 3, 4, 5])

print("Python List:", python_list)
print("NumPy Array:", numpy_array)

Python List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]


## 3. NumPy Arrays (ndarray)

A NumPy array is called an `ndarray`, which stands for N-dimensional array.

It can store data in one or more dimensions.

In [5]:
arr = np.array([10, 20, 30, 40])

print(arr)
print("Type:", type(arr))
print("Data type:", arr.dtype)

[10 20 30 40]
Type: <class 'numpy.ndarray'>
Data type: int64


## 4. Creating Arrays

NumPy provides several ways to create arrays, such as:

- `np.array()`
- `np.zeros()`
- `np.ones()`
- `np.arange()`
- `np.linspace()`

In [6]:
# Using np.array()
arr1 = np.array([1, 2, 3, 4, 5])

# Using np.zeros()
arr2 = np.zeros(5)

# Using np.ones()
arr3 = np.ones(5)

# Using np.arange()
arr4 = np.arange(1, 10)

# Using np.linspace()
arr5 = np.linspace(1, 10, 5)

print("array:", arr1)
print("zeros:", arr2)
print("ones:", arr3)
print("arange:", arr4)
print("linspace:", arr5)

array: [1 2 3 4 5]
zeros: [0. 0. 0. 0. 0.]
ones: [1. 1. 1. 1. 1.]
arange: [1 2 3 4 5 6 7 8 9]
linspace: [ 1.    3.25  5.5   7.75 10.  ]


## 5. Dimensions

The dimension of a NumPy array represents the number of levels in the array.

Examples:

- 0-D array → single value
- 1-D array → list of values
- 2-D array → rows and columns
- 3-D array → collection of 2-D arrays

In [7]:
arr_0d = np.array(10)

arr_1d = np.array([1, 2, 3, 4])

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("0-D:", arr_0d.ndim)
print("1-D:", arr_1d.ndim)
print("2-D:", arr_2d.ndim)

0-D: 0
1-D: 1
2-D: 2


## 6. Shape

The `shape` attribute returns the size of an array in each dimension.

In [8]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Array:")
print(arr)

print("Shape:", arr.shape)

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


## 7. Size

The `size` attribute returns the total number of elements in an array.

In [9]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Total elements:", arr.size)

Total elements: 6


## 8. Data Types

NumPy arrays have a data type that specifies the type of values stored in the array.

Common NumPy data types include:

- int
- float
- bool
- str

In [10]:
int_array = np.array([1, 2, 3])
float_array = np.array([1.1, 2.2, 3.3])
bool_array = np.array([True, False, True])

print("Integer:", int_array.dtype)
print("Float:", float_array.dtype)
print("Boolean:", bool_array.dtype)

Integer: int64
Float: float64
Boolean: bool


## 9. Indexing

Indexing is used to access individual elements of an array.

NumPy uses zero-based indexing, meaning the first element has index 0.

In [11]:
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])

First element: 10
Third element: 30
Last element: 50


## 10. Slicing

Slicing is used to access a range of elements from an array.

The syntax is:

`array[start:stop:step]`

In [12]:
arr = np.array([10, 20, 30, 40, 50])

print("First three:", arr[0:3])
print("From second element:", arr[1:])
print("Every second element:", arr[::2])

First three: [10 20 30]
From second element: [20 30 40 50]
Every second element: [10 30 50]


## 11. Reshaping

Reshaping changes the structure of an array without changing its data.

In [13]:
arr = np.arange(1, 13)

print("Original:")
print(arr)

reshaped = arr.reshape(3, 4)

print("Reshaped:")
print(reshaped)

Original:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 12. Flatten

The `flatten()` method converts a multidimensional array into a one-dimensional array.

In [14]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat = arr.flatten()

print("Original:")
print(arr)

print("Flattened:")
print(flat)

Original:
[[1 2 3]
 [4 5 6]]
Flattened:
[1 2 3 4 5 6]


## 13. Copy vs View

A copy creates a completely separate array.

A view creates another way of looking at the same underlying data.

Changes made to a copy do not affect the original array, while changes made through a view can affect the original array.

In [15]:
# Copy
arr = np.array([1, 2, 3, 4])

copy_arr = arr.copy()
copy_arr[0] = 100

print("Original after copy modification:", arr)
print("Copy:", copy_arr)

Original after copy modification: [1 2 3 4]
Copy: [100   2   3   4]


In [16]:
# View
arr = np.array([1, 2, 3, 4])

view_arr = arr.view()
view_arr[0] = 100

print("Original after view modification:", arr)
print("View:", view_arr)

Original after view modification: [100   2   3   4]
View: [100   2   3   4]


## 14. Broadcasting

Broadcasting allows NumPy to perform operations between arrays of different shapes when their dimensions are compatible.

In [17]:
arr = np.array([10, 20, 30, 40])

result = arr + 5

print("Original:", arr)
print("After adding 5:", result)

Original: [10 20 30 40]
After adding 5: [15 25 35 45]


## 15. Array Operations

NumPy supports arithmetic operations directly on arrays.

Common operations include:

- Addition
- Subtraction
- Multiplication
- Division
- Power

In [18]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]
Power: [100 400 900]


## 16. Universal Functions (ufuncs)

Universal functions, or ufuncs, are NumPy functions that operate element-by-element on arrays.

Examples include:

- `np.add()`
- `np.subtract()`
- `np.multiply()`
- `np.sqrt()`
- `np.exp()`
- `np.sin()`

In [19]:
arr = np.array([1, 4, 9, 16])

print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))

Square root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [20]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", np.add(a, b))
print("Subtraction:", np.subtract(a, b))
print("Multiplication:", np.multiply(a, b))

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
