# NumPy Mathematical Operations

NumPy provides many mathematical and statistical functions for working with numerical data.

In this notebook, we will learn how to perform statistical calculations, array operations, matrix operations, and basic linear algebra operations using NumPy.

In [1]:
import numpy as np

In [2]:
data = np.array([10, 20, 30, 40, 50])

print("Data:", data)

Data: [10 20 30 40 50]


## 1. Sum

The `np.sum()` function calculates the total of all elements in an array.

In [3]:
data = np.array([10, 20, 30, 40, 50])

total = np.sum(data)

print("Sum:", total)

Sum: 150


## 2. Mean

The mean, or average, is calculated by adding all values and dividing the total by the number of values.

NumPy provides the `np.mean()` function to calculate the mean.

In [4]:
mean_value = np.mean(data)

print("Mean:", mean_value)

Mean: 30.0


## 3. Median

The median is the middle value of a sorted dataset.

NumPy provides the `np.median()` function to calculate the median.

In [5]:
median_value = np.median(data)

print("Median:", median_value)

Median: 30.0


## 4. Variance

Variance measures how far the values in a dataset are spread out from the mean.

NumPy provides the `np.var()` function to calculate variance.

In [6]:
variance = np.var(data)

print("Variance:", variance)

Variance: 200.0


## 5. Standard Deviation

Standard deviation measures the amount of variation or dispersion in a dataset.

It is the square root of variance.

NumPy provides the `np.std()` function.

In [7]:
std_deviation = np.std(data)

print("Standard Deviation:", std_deviation)

Standard Deviation: 14.142135623730951


## 6. Minimum

The `np.min()` function returns the smallest value in an array.

In [8]:
minimum = np.min(data)

print("Minimum:", minimum)

Minimum: 10


## 7. Maximum

The `np.max()` function returns the largest value in an array.

In [9]:
maximum = np.max(data)

print("Maximum:", maximum)

Maximum: 50


## 8. Argmin

The `np.argmin()` function returns the index position of the smallest value in an array.

In [10]:
index_min = np.argmin(data)

print("Index of minimum value:", index_min)
print("Minimum value:", data[index_min])

Index of minimum value: 0
Minimum value: 10


## 9. Argmax

The `np.argmax()` function returns the index position of the largest value in an array.

In [11]:
index_max = np.argmax(data)

print("Index of maximum value:", index_max)
print("Maximum value:", data[index_max])

Index of maximum value: 4
Maximum value: 50


## 10. Percentile

A percentile indicates the value below which a certain percentage of observations fall.

NumPy provides the `np.percentile()` function.

In [12]:
percentile_50 = np.percentile(data, 50)
percentile_75 = np.percentile(data, 75)

print("50th Percentile:", percentile_50)
print("75th Percentile:", percentile_75)

50th Percentile: 30.0
75th Percentile: 40.0


## 11. Dot Product

The dot product multiplies corresponding elements of two arrays and then adds the results.

For example:

`[1, 2, 3] · [4, 5, 6]`

= `(1×4) + (2×5) + (3×6)`

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)

print("Dot Product:", dot_product)

Dot Product: 32


## 12. Matrix Multiplication

Matrix multiplication combines two matrices according to the rules of linear algebra.

NumPy provides `np.matmul()` and the `@` operator for matrix multiplication.

In [14]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = np.matmul(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Multiplication:")
print(result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Multiplication:
[[19 22]
 [43 50]]


In [15]:
result2 = A @ B

print(result2)

[[19 22]
 [43 50]]


## 13. Transpose

The transpose changes the rows of a matrix into columns and the columns into rows.

NumPy provides the `.T` attribute and `np.transpose()` function.

In [16]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original Matrix:")
print(matrix)

print("\nTranspose:")
print(matrix.T)

Original Matrix:
[[1 2 3]
 [4 5 6]]

Transpose:
[[1 4]
 [2 5]
 [3 6]]


## 14. Basic Linear Algebra Operations

NumPy provides several functions for basic linear algebra operations.

Some commonly used operations include:

- Matrix multiplication
- Dot product
- Determinant
- Inverse
- Solving linear equations

In [17]:
matrix = np.array([
    [1, 2],
    [3, 4]
])

determinant = np.linalg.det(matrix)

print("Determinant:", determinant)

Determinant: -2.0000000000000004


In [18]:
inverse = np.linalg.inv(matrix)

print("Inverse:")
print(inverse)

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


### Solving Linear Equations

NumPy can solve systems of linear equations using `np.linalg.solve()`.

In [19]:
A = np.array([
    [2, 1],
    [1, 3]
])

B = np.array([5, 6])

solution = np.linalg.solve(A, B)

print("Solution:", solution)

Solution: [1.8 1.4]
