03_NumPy_Random.ipynb

# NumPy Random Module

NumPy provides the `random` module for generating random numbers and performing random sampling.

The NumPy random module is useful in simulations, data analysis, machine learning, probability experiments, and testing.

In this notebook, we will learn about random numbers, random seeds, random integers, random choices, shuffling, permutations, and random probability distributions.

In [1]:
import numpy as np

## 1. Random Numbers

The `np.random.rand()` function generates random floating-point numbers between 0 and 1.

Each time the code is executed, different random values may be generated.

In [2]:
random_numbers = np.random.rand(5)

print("Random numbers:", random_numbers)

Random numbers: [0.6592823  0.78083988 0.60576644 0.26119146 0.5353866 ]


In [3]:
random_matrix = np.random.rand(2, 3)

print("Random 2D array:")
print(random_matrix)

Random 2D array:
[[0.5479925  0.09537918 0.53100415]
 [0.83094748 0.17883834 0.86502041]]


## 2. Random Seed

A random seed is used to make random number generation reproducible.

When the same seed is used, NumPy generates the same sequence of random numbers.

This is useful when we want to reproduce the same results during experiments and testing.

In [4]:
np.random.seed(42)

numbers1 = np.random.rand(5)

print("First sequence:")
print(numbers1)

First sequence:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [5]:
np.random.seed(42)

numbers2 = np.random.rand(5)

print("Second sequence:")
print(numbers2)

Second sequence:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [6]:
print("Are both sequences equal?", np.array_equal(numbers1, numbers2))

Are both sequences equal? True


## 3. Random Integers

The `np.random.randint()` function generates random integers within a specified range.

The upper limit is excluded.

In [7]:
random_integers = np.random.randint(1, 10, size=5)

print("Random integers:", random_integers)

Random integers: [3 7 8 5 4]


In [8]:
random_matrix = np.random.randint(1, 100, size=(3, 3))

print("Random integer matrix:")
print(random_matrix)

Random integer matrix:
[[24  3 22]
 [53  2 88]
 [30 38  2]]


## 4. Random Choice

The `np.random.choice()` function randomly selects elements from an array.

It can be used for random sampling.

In [9]:
colors = np.array(["Red", "Green", "Blue", "Yellow"])

choice = np.random.choice(colors)

print("Random choice:", choice)

Random choice: Yellow


In [10]:
choices = np.random.choice(colors, size=3)

print("Random choices:", choices)

Random choices: ['Yellow' 'Red' 'Red']


In [11]:
choices = np.random.choice(colors, size=5, replace=True)

print("Random choices with replacement:", choices)

Random choices with replacement: ['Yellow' 'Green' 'Green' 'Red' 'Yellow']


## 5. Shuffle

The `np.random.shuffle()` function randomly changes the order of elements in an array.

The shuffle operation modifies the original array.

In [12]:
numbers = np.array([1, 2, 3, 4, 5])

print("Before shuffle:")
print(numbers)

np.random.shuffle(numbers)

print("After shuffle:")
print(numbers)

Before shuffle:
[1 2 3 4 5]
After shuffle:
[2 4 3 5 1]


## 6. Permutation

The `np.random.permutation()` function returns a randomly rearranged copy of an array.

Unlike `shuffle()`, permutation does not modify the original array.

In [13]:
numbers = np.array([1, 2, 3, 4, 5])

permuted = np.random.permutation(numbers)

print("Original array:")
print(numbers)

print("Permuted array:")
print(permuted)

Original array:
[1 2 3 4 5]
Permuted array:
[1 5 3 4 2]


## 7. Random Distributions

A probability distribution describes how random values are distributed.

NumPy provides several probability distributions through the `np.random` module.

Some commonly used distributions are:

- Normal distribution
- Uniform distribution
- Binomial distribution
- Poisson distribution

### Normal Distribution

A normal distribution is a continuous probability distribution that is commonly used in statistics and data analysis.

It is defined using a mean and standard deviation.

In [14]:
normal_data = np.random.normal(loc=50, scale=10, size=1000)

print("First 10 values:")
print(normal_data[:10])

First 10 values:
[52.22078902 42.32023498 51.42464602 49.65347816 61.34339266 48.95254452
 44.74877149 69.12771271 29.73280384 61.19423612]


In [15]:
print("Mean:", np.mean(normal_data))
print("Standard deviation:", np.std(normal_data))

Mean: 50.439215853902205
Standard deviation: 10.540087458496114


### Uniform Distribution

A uniform distribution generates values where each value within a specified range has an equal probability of being selected.

In [16]:
uniform_data = np.random.uniform(1, 10, size=10)

print("Uniform random values:")
print(uniform_data)

Uniform random values:
[6.94738106 5.97701307 6.37728276 8.05449298 5.32813448 1.36678695
 2.47599533 4.94746495 7.52343904 6.33950783]


### Binomial Distribution

The binomial distribution models the number of successes in a fixed number of independent trials.

It requires:

- Number of trials
- Probability of success

In [17]:
binomial_data = np.random.binomial(n=10, p=0.5, size=10)

print("Binomial values:")
print(binomial_data)

Binomial values:
[6 5 5 4 5 6 7 5 2 3]


### Poisson Distribution

The Poisson distribution is commonly used to model the number of events occurring within a fixed interval of time or space.

In [18]:
poisson_data = np.random.poisson(lam=3, size=10)

print("Poisson values:")
print(poisson_data)

Poisson values:
[0 4 2 2 7 2 6 4 4 2]


## Practical Example

Suppose we want to randomly select students from a class for an activity.

We can use NumPy's random choice function to select students randomly.

In [19]:
students = np.array([
    "Student1",
    "Student2",
    "Student3",
    "Student4",
    "Student5"
])

np.random.seed(42)

selected_students = np.random.choice(students, size=2, replace=False)

print("Selected students:")
print(selected_students)

Selected students:
['Student2' 'Student5']
