In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [2]:
my_list = [1, 2, 3]
my_array = np.array([1, 2, 3])

print(my_list * 2)
print(my_array * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [3]:
arr = np.array([10, 20, 30])
print(arr + 5)

[15 25 35]


In [4]:
import pandas as pd

series = pd.Series([80, 90, 75])
df = pd.DataFrame({
    "Name": ["Ram", "Sam", "Ravi"],
    "Marks": [80, 90, 75]
})

print(series)
print(df)

0    80
1    90
2    75
dtype: int64
   Name  Marks
0   Ram     80
1   Sam     90
2  Ravi     75


In [5]:
df = pd.read_csv("students.csv")
print(df.head())

      Name  Age  Marks
0    Alice   20     85
1      Bob   21     90
2  Charlie   22     78
3    David   23     92


In [6]:
df1 = pd.DataFrame({
    "ID": [1, 2],
    "Name": ["Ram", "Sam"]
})

df2 = pd.DataFrame({
    "ID": [1, 2],
    "Marks": [85, 90]
})

result = pd.merge(df1, df2, on="ID")
print(result)

   ID Name  Marks
0   1  Ram     85
1   2  Sam     90


In [7]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR"],
    "Marks": [80, 70, 90, 75]
})

print(df.groupby("Department")["Marks"].mean())

Department
HR    72.5
IT    85.0
Name: Marks, dtype: float64


In [8]:
df = pd.DataFrame({
    "Name": ["Ram", "Sam", "Ravi"],
    "Marks": [80, 70, 90],
    "Age": [21, 22, 19]
})

result = df[(df["Marks"] > 75) & (df["Age"] > 20)]
print(result)

  Name  Marks  Age
0  Ram     80   21


In [9]:
df = pd.DataFrame({
    "Name": ["Ram", "Sam", "Ravi"],
    "Marks": [80, np.nan, 90]
})

print(df.isnull().sum())
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
print(df)

Name     0
Marks    1
dtype: int64
   Name  Marks
0   Ram   80.0
1   Sam   85.0
2  Ravi   90.0


In [10]:
arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

Sum: 150
Mean: 30.0
Median: 30.0
Variance: 200.0
Standard Deviation: 14.142135623730951


In [11]:
df = pd.DataFrame({
    "Age": [20, 25, 30, 35, 40],
    "Department": ["IT", "HR", "IT", "HR", "IT"]
})

print("Before optimization:")
print(df.memory_usage(deep=True).sum())

df["Age"] = df["Age"].astype("int8")
df["Department"] = df["Department"].astype("category")

print("After optimization:")
print(df.memory_usage(deep=True).sum())

Before optimization:
222
After optimization:
163
